version: "3.7"

services:
  http-service:
    build:
      context: ./app/http-service
    env_file:
      - ./app/http-service/.env
    volumes:
      - ./app/http-service:/app:delegated
    ports:
      - "3000:3000"
    networks: 
      - stocks
  stocks-service:
    build:
      context: ./app/stocks-service
    env_file:
      - ./app/stocks-service/.env
    depends_on:
      - redis
    volumes:
      - ./app/stocks-service:/app:delegated
    networks: 
      - stocks
  finnhub-service:
    build:
      context: ./app/finnhub-service
    env_file:
      - ./app/finnhub-service/.env
    depends_on: :
      - redis
    volumes:
      - ./app/finnhub-service:/app:delegated
    networks:
      - stocks
    
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    expose: 
      - 5672
    ports:
      - "15672:15672"
    hostname: rabbit
    networks:
      - stocks
  redis:
    image: redis:6-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379
    networks:
      - stocks

networks:
  stocks: {}
volumes:
  mongo-data: ~
  redis-data: